### ISSUE TITLE
Money Problem

### ISSUE THREAD

**Issue by Blueeyestar** [GentleGravel/BuyRegion#2]
Hello  I am currently testing the BuyRegion with the 1.14 and Red-Protec
Almost everything's going well.   The renter gets money deducted but the zone owner doesn't get money.

**Comment by dsevillamartin** [comment]
You mean using the code by @FabioZumbi12 at https://github.com/GentleGravel/BuyRegion/pull/1 ? If you are having issues with that, I'd comment that on the PR so that can be fixed before releasing a 1.14 version.
