### ISSUE TITLE
Rental is defective!

### ISSUE THREAD

**Issue by Blueeyestar** [GentleGravel/BuyRegion#4]
I have created zones with Red Protec, and set them to 30 days. But if the user rent it then he rents it for 9 years!!!

![2019-05-29_10 15 54](https://user-images.githubusercontent.com/35557302/58541138-1cb66280-81fb-11e9-945f-a736476b3fa7.png)
![2019-05-29_10 15 09](https://user-images.githubusercontent.com/35557302/58541144-1fb15300-81fb-11e9-90b9-24996311d504.png)

**Comment by dsevillamartin** [comment]
Did you figure out the issue?

**Comment by Blueeyestar** [comment]
it was an embarrassing problem i just took the wrong date format. the plugin does its job very well. I have a question how can players extend their zone they have rented? do they have to wait until the time is up?

**Comment by dsevillamartin** [comment]
@Blueeyestar as the zone if configured by a region with either WorldGuard of RedProtect, I think the only way of expanding would be to expand the region itself... as far as I'm aware, it's not possible in GentleGravel. Expanding the region before the time is up should still work as intended, as the positions aren't saved by the plugin.
